import CartPage from 'components/cart';
import Head from 'next/head';

export default function Cart() {
  return (
    <>
      <Head>
        <title>Cart</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <CartPage />
    </>
  );
}
