import SingleProductPage from 'components/product/single-product';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function SingleProduct() {
  const router = useRouter();
  const { id } = router.query;
  let productId: string;

  if (!id) {
    return;
  }

  return (
    <>
      <Head>
        <title>Single product</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <SingleProductPage id={Array.isArray(id) ? id[0] : id} />
    </>
  );
}
